# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: tyesample
services:
- name: webapp
  project: WebApp/WebApp.csproj
- name: productservice
  project: ProductService/ProductService.csproj
- name: postgres
  image: postgres
  env:
  - name: POSTGRES_PASSWORD
    value: "pass@word1"
  bindings:
  - port: 5432
    connectionString: Host=${host};Port=${port};Database=productdb;Username=postgres;Password=${env:POSTGRES_PASSWORD} 
    
